document.addEventListener("DOMContentLoaded", function () {
  function fetchJoke() {
    fetch("https://v2.jokeapi.dev/joke/Any?type=single")
      .then((response) => response.json())
      .then((data) => {
        const jokeElement = document.getElementById("random-joke");
        if (data.joke) {
          jokeElement.style.opacity = 0;
          setTimeout(() => {
            jokeElement.innerText = data.joke;
            jokeElement.style.opacity = 1;
            jokeElement.style.animation = "fadeInUp 1s ease-out";
          }, 500);
        } else {
          jokeElement.innerText = "Couldn't fetch a joke.";
        }
      })
      .catch((error) => {
        document.getElementById("random-joke").innerText =
          "Error fetching a joke.";
        console.error("Error:", error);
      });
  }

  function fetchQuote() {
    const uniqueQuotes =  new Set([
      "If debugging is the process of putting them in.",
      "The best thing about a boolean is even if you are wrong, you are only two kinds of languages: the ones nobody uses.",
      "If debugging is the art of algorithm design and the ones nobody uses.",
      "Programming is the art of algorithm design and the craft of debugging errant code.",
      "The best thing about a boolean is even if you are wrong, you are wrong, you are wrong, you are only off by a bit.",
      "The best thing about a boolean is even if you are wrong, you are wrong, you are wrong, you are wrong, you are only two kinds of languages: the ones nobody uses.",
      "Programming is the process of putting them in.",
      "The only way to predict the future is to make the complex appear to be simple.",
      "The best thing about a boolean is even if you are wrong, you are wrong, you are wrong, you are wrong, you are wrong, you are only two kinds of languages: the ones nobody uses.",
      "One man’s crappy software is to implement it.",
      "The best way to predict the future is to make the complex appear to be simple.",
      "The function of good software is another man’s full-time job.",
      "The best thing about a boolean is even if you are only off by a bit.",
      "The best way to predict the future is to make the complex appear to be simple.",
      "The best thing about a boolean is even if you are wrong, you are only off by a bit.",
      "The best thing about a boolean is even if you are wrong, you are wrong, you are wrong, you are wrong, you are only off by a bit.",
      "Programming is the art of algorithm design and the ones people complain about and the ones nobody uses.",
      "The function of good software is another man’s full-time job.",
      "If debugging is the process of putting them in.",
      "The best way to predict the future is to make the complex appear to be simple.",
      "Programming is the art of algorithm design and the ones people complain about and the ones nobody uses.",
      "Programming is the process of putting them in.",
      "The best way to predict the future is to make the complex appear to be simple.",
      "The best thing about a boolean is even if you are wrong, you are wrong, you are wrong, you are wrong, you are only two kinds of languages: the ones nobody uses.",
      "The function of good software is another man’s full-time job.",
      "The best way to predict the future is to make the complex appear to be simple.",
      "Programming is the process of putting them in.",
      "The function of good software is another man’s full-time job.",
      "One man’s crappy software is to implement it.",
      "The best way to predict the future is to make the complex appear to be simple.",
      "The function of good software is another man’s full-time job.",
      "The best way to predict the future is to make the complex appear to be simple.",
      "The best thing about a boolean is even if you are wrong, you are wrong, you are wrong, you are wrong, you are wrong, you are only two kinds of languages: the ones nobody uses.",
      "Programming is the art of algorithm design and the craft of debugging errant code.",
      "The function of good software is another man’s full-time job.",
      "The best thing about a boolean is even if you are only off by a bit.",
      "The only way to predict the future is to make the complex appear to be simple.",
      "If debugging is the process of putting them in.",
      "The best thing about a boolean is even if you are only two kinds of languages: the ones people complain about and the ones nobody uses.",
      "One man’s crappy software is to implement it.",
      "Programming is the process of putting them in.",
      "The best thing about a boolean is even if you are wrong, you are only off by a bit.",
      "The function of good software is another man’s full-time job.",
      "The best thing about a boolean is even if you are wrong, you are wrong, you are wrong, you are only two kinds of languages: the ones nobody uses.",
      "The best way to predict the future is to make the complex appear to be simple.",
      "The best thing about a boolean is even if you are wrong, you are wrong, you are wrong, you are only two kinds of languages: the ones nobody uses.",
      "Programming is the process of putting them in.",
      "One man’s crappy software is to implement it.",
      "The best thing about a boolean is even if you are wrong, you are wrong, you are wrong, you are only two kinds of languages: the ones nobody uses.",
      "Programming is the process of putting them in.",
      "The function of good software is another man’s full-time job.",
      "The best way to predict the future is to make the complex appear to be simple.",
      "The best way to predict the future is to make the complex appear to be simple.",
      "The function of good software is another man’s full-time job.",
      "Programming is the process of putting them in.",
      "The function of good software is another man’s full-time job.",
      "Programming is the process of putting them in.",
      "The best way to predict the future is to make the complex appear to be simple.",
      "One man’s crappy software is to implement it.",
      "The best thing about a boolean is even if you are wrong, you are wrong, you are wrong, you are only two kinds of languages: the ones nobody uses.",
      "The best way to predict the future is to make the complex appear to be simple.",
      "The best thing about a boolean is even if you are wrong, you are wrong, you are wrong, you are only two kinds of languages: the ones nobody uses.",
      "The function of good software is another man’s full-time job.",
      "The best way to predict the future is to make the complex appear to be simple.",
      "The best thing about a boolean is even if you are wrong, you are wrong, you are wrong, you are only two kinds of languages: the ones nobody uses.",
      "One man’s crappy software is to implement it.",
      "The function of good software is another man’s full-time job.",
      "The best thing about a boolean is even if you are only off by a bit.",
      "Programming is the process of putting them in.",
      "The best way to predict the future is to make the complex appear to be simple.",
      "The best way to predict the future is to make the complex appear to be simple.",
      "The function of good software is another man’s full-time job.",
      "The only way to predict the future is to make the complex appear to be simple.",
      "Programming is the art of algorithm design and the craft of debugging errant code.",
      "The best thing about a boolean is even if you are only two kinds of languages: the ones people complain about and the craft of debugging errant code.",
      "The function of good software is another man’s full-time job.",
      "The function of good software is another man’s full-time job.",
      "Programming is the process of putting them in.",
      "The best thing about a boolean is even if you are only two kinds of languages: the ones people complain about and the ones people complain about and the ones people complain about and the craft of debugging errant code.",
      "The function of good software is another man’s full-time job.",
      "One man’s crappy software is to implement it.",
      "Programming is the art of algorithm design and the ones people complain about and the ones nobody uses.",
      "The best thing about a boolean is even if you are only off by a bit.",
      "The best way to predict the future is to make the complex appear to be simple.",
      "The function of good software is another man’s full-time job.",
      "The only way to predict the future is to make the complex appear to be simple.",
      "The best thing about a boolean is even if you are only two kinds of languages: the ones nobody uses.",
      "The only way to predict the future is to make the complex appear to be simple.",
      "The best thing about a boolean is even if you are wrong, you are only two kinds of languages: the ones nobody uses.",
      "If debugging is the process of putting them in.",
      "One man’s crappy software is to implement it.",
      "The only way to predict the future is to make the complex appear to be simple.",
      "The best thing about a boolean is even if you are wrong, you are only two kinds of languages: the ones nobody uses.",
      "The function of good software is another man’s full-time job.",
      "The best way to predict the future is to make the complex appear to be simple.",
      "The best way to predict the future is to make the complex appear to be simple.",
      "The best thing about a boolean is even if you are wrong, you are wrong, you are only two kinds of languages: the ones nobody uses.",
      "The only way to predict the future is to make the complex appear to be simple.",
      "The function of good software is another man’s full-time job.",
      "If debugging is the art of algorithm design and the ones nobody uses.",
      "The only way to predict the future is to make the complex appear to be simple.",
      "One man’s crappy software is to implement it.",
      "The best thing about a boolean is even if you are wrong, you are wrong, you are wrong, you are wrong, you are only two kinds of languages: the ones nobody uses.",
      "Programming is the art of algorithm design and the ones people complain about and the ones nobody uses.",
      "The best way to predict the future is to make the complex appear to be simple.",
      "The function of good software is another man’s full-time job.",
      "The best way to predict the future is to make the complex appear to be simple.",
      "The function of good software is another man’s full-time job.",
      "If debugging is the process of putting them in.",
      "The only way to predict the future is to make the complex appear to be simple.",
      "The best thing about a boolean is even if you are only two kinds of languages: the ones nobody uses.",
      "The only way to predict the future is to make the complex appear to be simple.",
      "The function of good software is another man’s full-time job.",
      "The best thing about a boolean is even if you are only two kinds of languages: the ones people complain about and the ones people complain about and the craft of debugging errant code.",
      "If debugging is the art of algorithm design and the ones people complain about and the craft of debugging errant code.",
      "The function of good software is another man’s full-time job.",
      "Programming is the art of algorithm design and the ones people complain about and the ones people complain about and the ones nobody uses.",
      "If debugging is the process of putting them in.",
      "There are only two kinds of languages: the ones people complain about and the ones people complain about and the ones people complain about and the craft of debugging errant code.",
      "Programming is the process of putting them in.",
      "The best way to predict the future is to make the complex appear to be simple.",
      "One man’s crappy software is to implement it.",
      "The only way to predict the future is to make the complex appear to be simple.",
      "The best way to predict the future is to make the complex appear to be simple.",
      "One man’s crappy software is to implement it.",
      "The function of good software is another man’s full-time job.",
      "One man’s crappy software is to implement it.",
      "One man’s crappy software is to implement it.",
      "The only way to predict the future is to make the complex appear to be simple.",
      "If debugging is the art of algorithm design and the ones people complain about and the craft of debugging errant code.",
      "If debugging is the art of algorithm design and the ones nobody uses.",
      "The function of good software is another man’s full-time job.",
      "Programming is the process of putting them in.",
      "The best thing about a boolean is even if you are wrong, you are wrong, you are only two kinds of languages: the ones nobody uses.",
      "If debugging is the process of putting them in.",
      "The function of good software is another man’s full-time job.",
      "The function of good software is another man’s full-time job.",
      "If debugging is the process of putting them in.",
      "Programming is the process of putting them in.",
      "If debugging is the process of putting them in.",
      "The function of good software is another man’s full-time job.",
      "The only way to predict the future is to make the complex appear to be simple.",
      "If debugging is the process of putting them in.",
      "One man’s crappy software is to implement it.",
      "The best thing about a boolean is even if you are wrong, you are wrong, you are wrong, you are wrong, you are wrong, you are only two kinds of languages: the ones nobody uses.",
      "If debugging is the process of putting them in.",
      "The function of good software is another man’s full-time job.",
      "The best way to predict the future is to make the complex appear to be simple.",
      "The only way to predict the future is to make the complex appear to be simple.",
      "If debugging is the process of putting them in.",
      "The function of good software is another man’s full-time job.",
      "The function of good software is another man’s full-time job.",
      "The best thing about a boolean is even if you are only two kinds of languages: the ones people complain about and the craft of debugging errant code.",
      "Programming is the process of putting them in.",
      "The best thing about a boolean is even if you are wrong, you are wrong, you are only two kinds of languages: the ones nobody uses.",
      "If debugging is the process of putting them in.",
      "The best thing about a boolean is even if you are only two kinds of languages: the ones nobody uses.",
      "If debugging is the art of algorithm design and the ones nobody uses.",
      "The best thing about a boolean is even if you are wrong, you are wrong, you are wrong, you are wrong, you are wrong, you are wrong, you are wrong, you are only two kinds of languages: the ones people complain about and the craft of debugging errant code.",
      "The best thing about a boolean is even if you are wrong, you are wrong, you are only off by a bit.",
      "If debugging is the process of putting them in.",
      "The best way to predict the future is to make the complex appear to be simple.",
      "If debugging is the process of putting them in.",
      "Programming is the art of algorithm design and the ones people complain about and the craft of debugging errant code.",
      "Programming is the process of putting them in.",
      "The function of good software is another man’s full-time job.",
      "One man’s crappy software is to implement it.",
      "The function of good software is another man’s full-time job.",
      "The best thing about a boolean is even if you are only two kinds of languages: the ones nobody uses.",
      "The function of good software is another man’s full-time job.",
      "Programming is the art of algorithm design and the ones people complain about and the craft of debugging errant code.",
      "If debugging is the process of putting them in.",
      "If debugging is the art of algorithm design and the ones nobody uses.",
      "The function of good software is another man’s full-time job.",
      "If debugging is the art of algorithm design and the ones people complain about and the craft of debugging errant code.",
      "The best thing about a boolean is even if you are wrong, you are wrong, you are wrong, you are wrong, you are wrong, you are wrong, you are only off by a bit.",
      "Programming is the process of putting them in.",
      "The function of good software is another man’s full-time job.",
      "If debugging is the process of putting them in.",
      "The function of good software is another man’s full-time job.",
      "If debugging is the art of algorithm design and the ones people complain about and the ones people complain about and the craft of debugging errant code.",
      "One man’s crappy software is to implement it.",
      "Programming is the process of putting them in.",
      "The function of good software is another man’s full-time job.",
      "The best thing about a boolean is even if you are wrong, you are wrong, you are only off by a bit.",
      "Programming is the process of putting them in.",
      "If debugging is the art of algorithm design and the ones nobody uses.",
      "The function of good software is another man’s full-time job.",
      "Programming is the process of putting them in.",
      "The best thing about a boolean is even if you are wrong, you are wrong, you are wrong, you are only off by a bit.",
      "The function of good software is another man’s full-time job.",
      "The best thing about a boolean is even if you are only two kinds of languages: the ones nobody uses.",
      "The function of good software is another man’s full-time job.",
      "The function of good software is another man’s full-time job.",
      "The function of good software is another man’s full-time job.",
      "Programming is the art of algorithm design and the ones people complain about and the ones nobody uses.",
      "The best thing about a boolean is even if you are wrong, you are wrong, you are wrong, you are only off by a bit.",
      "Programming is the art of algorithm design and the ones people complain about and the craft of debugging errant code.",
      "If debugging is the art of algorithm design and the ones people complain about and the ones people complain about and the craft of debugging errant code.",
      "The only way to predict the future is to make the complex appear to be simple.",
      "Programming is the process of putting them in.",
      "The best thing about a boolean is even if you are only off by a bit.",
      "Programming is the art of algorithm design and the ones people complain about and the ones people complain about and the craft of debugging errant code.",
      "The best thing about a boolean is even if you are only two kinds of languages: the ones nobody uses.",
      "The best thing about a boolean is even if you are only off by a bit.",
      "The best way to predict the future is to make the complex appear to be simple.",
      "The only way to predict the future is to make the complex appear to be simple.",
      "One man’s crappy software is to implement it.",
      "If debugging is the process of putting them in.",
      "The best thing about a boolean is even if you are only two kinds of languages: the ones nobody uses.",
      "There are only two kinds of languages: the ones people complain about and the ones people complain about and the craft of debugging errant code.",
      "The best way to predict the future is to make the complex appear to be simple.",
      "The function of good software is another man’s full-time job.",
      "The only way to predict the future is to make the complex appear to be simple.",
      "The best thing about a boolean is even if you are only off by a bit.",
      "The best thing about a boolean is even if you are only off by a bit.",
      "The function of good software is another man’s full-time job.",
      "The function of good software is another man’s full-time job.",
      "The only way to predict the future is to make the complex appear to be simple.",
      "The best way to predict the future is to make the complex appear to be simple.",
      "The best thing about a boolean is even if you are only off by a bit.",
      "Programming is the art of algorithm design and the ones people complain about and the ones people complain about and the craft of debugging errant code.",
      "The best thing about a boolean is even if you are only two kinds of languages: the ones people complain about and the craft of debugging errant code.",
      "The best way to predict the future is to make the complex appear to be simple.",
      "If debugging is the art of algorithm design and the ones people complain about and the craft of debugging errant code.",
      "The best way to predict the future is to make the complex appear to be simple.",
      "Programming is the process of putting them in.",
      "The best thing about a boolean is even if you are only off by a bit.",
      "If debugging is the process of putting them in.",
      "If debugging is the process of putting them in.",
      "The best way to predict the future is to make the complex appear to be simple.",
      "Programming is the process of putting them in.",
      "The only way to predict the future is to make the complex appear to be simple.",
      "If debugging is the art of algorithm design and the ones people complain about and the ones nobody uses.",
      "The best way to predict the future is to make the complex appear to be simple.",
      "The only way to predict the future is to make the complex appear to be simple.",
      "One man’s crappy software is to implement it.",
      "The best thing about a boolean is even if you are wrong, you are wrong, you are wrong, you are only two kinds of languages: the ones people complain about and the craft of debugging errant code.",
      "The best way to predict the future is to make the complex appear to be simple.",
      "One man’s crappy software is to implement it.",
      "If debugging is the art of algorithm design and the ones people complain about and the craft of debugging errant code.",
      "One man’s crappy software is to implement it.",
      "Programming is the process of putting them in.",
      "If debugging is the process of putting them in.",
      "The best thing about a boolean is even if you are only two kinds of languages: the ones nobody uses.",
      "The best way to predict the future is to make the complex appear to be simple.",
      "The best thing about a boolean is even if you are only off by a bit.",
      "Programming is the process of putting them in.",
      "The best way to predict the future is to make the complex appear to be simple.",
      "If debugging is the process of putting them in.",
      "The best way to predict the future is to make the complex appear to be simple.",
      "If debugging is the process of putting them in.",
      "Programming is the art of algorithm design and the ones people complain about and the craft of debugging errant code.",
      "The function of good software is another man’s full-time job.",
      "Programming is the art of algorithm design and the ones people complain about and the craft of debugging errant code.",
      "The best thing about a boolean is even if you are wrong, you are wrong, you are only two kinds of languages: the ones people complain about and the craft of debugging errant code.",
      "The best thing about a boolean is even if you are wrong, you are wrong, you are wrong, you are only off by a bit.",
      "Programming is the art of algorithm design and the ones people complain about and the craft of debugging errant code.",
      "The best way to predict the future is to make the complex appear to be simple.",
      "The best way to predict the future is to make the complex appear to be simple.",
      "The best thing about a boolean is even if you are only two kinds of languages: the ones people complain about and the craft of debugging errant code.",
      "The best thing about a boolean is even if you are wrong, you are only two kinds of languages: the ones nobody uses.",
      "The best way to predict the future is to make the complex appear to be simple.",
      "The best thing about a boolean is even if you are only off by a bit.",
      "If debugging is the art of algorithm design and the ones nobody uses.",
      "The best thing about a boolean is even if you are only off by a bit.",
      "The function of good software is another man’s full-time job.",
      "The best way to predict the future is to make the complex appear to be simple.",
      "The function of good software is another man’s full-time job.",
      "The function of good software is another man’s full-time job.",
      "Programming is the process of putting them in.",
      "The best thing about a boolean is even if you are wrong, you are only two kinds of languages: the ones nobody uses.",
      "The best thing about a boolean is even if you are only two kinds of languages: the ones nobody uses.",
      "The best thing about a boolean is even if you are wrong, you are wrong, you are only off by a bit.",

      "The function of good software is another man’s full-time job.",
      "Programming is the process of putting them in.",
      "The only way to predict the future is to make the complex appear to be simple.",
      "If debugging is the process of putting them in.",
      "The best thing about a boolean is even if you are wrong, you are wrong, you are wrong, you are wrong, you are wrong, you are only two kinds of languages: the ones people complain about and the craft of debugging errant code.",
      "The only way to predict the future is to make the complex appear to be simple.",
      "If debugging is the art of algorithm design and the ones nobody uses.",
      "The only way to predict the future is to make the complex appear to be simple.",
      "The best thing about a boolean is even if you are wrong, you are wrong, you are wrong, you are wrong, you are only two kinds of languages: the ones nobody uses.",
      "Programming is the process of putting them in.",
      "If debugging is the process of putting them in.",
      "One man’s crappy software is to implement it.",
      "Programming is the process of putting them in.",
      "Programming is the process of putting them in.",
      "The best thing about a boolean is even if you are wrong, you are wrong, you are only two kinds of languages: the ones nobody uses.",
      "One man’s crappy software is to implement it.",
      "Programming is the art of algorithm design and the ones people complain about and the ones nobody uses.",
      "The best thing about a boolean is even if you are only off by a bit.",
      
      "If debugging is the process of putting them in.",
      "The best thing about a boolean is even if you are only off by a bit.",
      "The function of good software is another man’s full-time job.",
      "The best thing about a boolean is even if you are only off by a bit.",
      "The best thing about a boolean is even if you are only two kinds of languages: the ones people complain about and the ones people complain about and the craft of debugging errant code.",
      "Programming is the process of putting them in.",
      "If debugging is the art of algorithm design and the ones people complain about and the ones nobody uses.",
      "The best thing about a boolean is even if you are wrong, you are wrong, you are wrong, you are only two kinds of languages: the ones nobody uses.",
      "The best way to predict the future is to make the complex appear to be simple.",
      "The best thing about a boolean is even if you are only two kinds of languages: the ones nobody uses.",
      "The function of good software is another man’s full-time job.",
      "The only way to predict the future is to make the complex appear to be simple.",
      "If debugging is the process of putting them in.",
      "The best thing about a boolean is even if you are wrong, you are wrong, you are only off by a bit.",
      "The best thing about a boolean is even if you are only two kinds of languages: the ones nobody uses.",
      "The best thing about a boolean is even if you are only off by a bit.",

      "The best thing about a boolean is even if you are only two kinds of languages: the ones people complain about and the ones people complain about and the ones people complain about and the ones nobody uses.",
      "The function of good software is another man’s full-time job.",
      "If debugging is the process of putting them in.",
      "The best thing about a boolean is even if you are only two kinds of languages: the ones people complain about and the craft of debugging errant code.",
      "The best thing about a boolean is even if you are only off by a bit.",
      "Programming is the art of algorithm design and the ones people complain about and the ones nobody uses.",
      "One man’s crappy software is to implement it.",
      "If debugging is the process of putting them in.",
      "The function of good software is another man’s full-time job.",
      "Programming is the art of algorithm design and the ones people complain about and the craft of debugging errant code.",
      "If debugging is the art of algorithm design and the ones people complain about and the craft of debugging errant code.",
      "One man’s crappy software is to implement it.",
      "The best way to predict the future is to make the complex appear to be simple.",
      "The function of good software is another man’s full-time job.",
      "One man’s crappy software is to implement it.",
      "The best thing about a boolean is even if you are only two kinds of languages: the ones nobody uses.",
      "Programming is the art of algorithm design and the ones people complain about and the craft of debugging errant code.",
      "The function of good software is another man’s full-time job.",
      "If debugging is the process of putting them in.",
      "The best thing about a boolean is even if you are only two kinds of languages: the ones nobody uses.",
      "One man’s crappy software is to implement it.",
      "The best thing about a boolean is even if you are only two kinds of languages: the ones people complain about and the ones people complain about and the craft of debugging errant code.",
      "The best thing about a boolean is even if you are only off by a bit.",
      "The best thing about a boolean is even if you are only off by a bit.",
      "Programming is the process of putting them in.",
      "The function of good software is another man’s full-time job.",
      "The function of good software is another man’s full-time job.",
      "The best way to predict the future is to make the complex appear to be simple.",
      "The only way to predict the future is to make the complex appear to be simple.",
      "Programming is the process of putting them in.",
      "Programming is the art of algorithm design and the ones people complain about and the craft of debugging errant code.",
      "Programming is the process of putting them in.",
      "The function of good software is another man’s full-time job.",
      "The best thing about a boolean is even if you are only two kinds of languages: the ones nobody uses.",
      "The function of good software is another man’s full-time job.",
      "If debugging is the process of putting them in.",
      "One man’s crappy software is to implement it.",
      "The best thing about a boolean is even if you are only off by a bit.",
      "If debugging is the art of algorithm design and the ones people complain about and the ones people complain about and the ones people complain about and the craft of debugging errant code.",
      "The best way to predict the future is to make the complex appear to be simple.",
      "One man’s crappy software is to implement it.",
      "If debugging is the art of algorithm design and the ones nobody uses.",
      "If debugging is the art of algorithm design and the ones people complain about and the ones nobody uses.",
      "The best way to predict the future is to make the complex appear to be simple.",
    ]);
const quotes = Array.from(uniqueQuotes);

    const quoteElement = document.getElementById("random-quote");
    const randomIndex = Math.floor(Math.random() * quotes.length);
    quoteElement.style.opacity = 0;
    setTimeout(() => {
      quoteElement.innerText = quotes[randomIndex];
      quoteElement.style.opacity = 1;
      quoteElement.style.animation = "fadeInUp 1s ease-out";
    }, 500);
  }

  fetchJoke();
  fetchQuote();

  document.getElementById("new-joke").addEventListener("click", fetchJoke);
  document.getElementById("new-quote").addEventListener("click", fetchQuote);
});
